version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: saml_idp_rails
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: samladmin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c 'rm -rf tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3456:3000"
    environment:
      RAILS_ENV: development
    env_file:
      - .env
    volumes:
      - .:/saml-idp-rails
      - bundle:/usr/local/bundle
volumes:
  bundle:
